### ISSUE TITLE
Changes to be pushed - To-Do

### ISSUE THREAD

**Issue by PreetAsari15** [PreetAsari15/dashboard#24]
- [ ] Git Pull

Create new folders in landing-pg:

- [ ] Components: Add Navbar.jsx, button.jsx, Header.jsx, Service.jsx, Footer.jsx
- [ ] Screens: Home.jsx
- [ ] Import all these files in App.js
- [ ] Create PR when all the above are done and prompt @PreetAsari15
